[buildPlans.iosevka-mayukai] # <iosevka-custom> is your plan name
design = [
  "ss09",
  "v-i-zshaped",
  "v-l-zshaped",
  "v-u-without-bar",
  "v-zero-reverse-slashed",
  "v-dollar-open",
  "v-three-flattop",
  "v-r-straight",
  "v-six-straight-bar",
  "v-nine-straight-bar",
  "v-capital-g-toothless",
  "v-one-base",
  "v-four-closed-non-crossing",
  "v-capital-b-more-asymmetric",
  "v-b-toothless-rounded",
  "v-d-toothless-rounded",
  "v-g-earless-rounded",
  "v-p-earless-rounded",
  "v-q-earless-corner",
  "ligset-dlig",
  "v-y-straight-turn",
  "v-a-doublestorey-toothless-rounded",
  "v-m-earless-rounded-double-arch",
  "v-n-earless-rounded-straight",
  "v-r-earless-rounded",
] # Customize styles
family = "Iosevka Mayukai" # Font menu family name
hintParams = ["-a", "sss"] # Optional custom parameters for ttfautohint
italic = [
  "v-i-zshaped",
  "v-one-base",
  "v-b-toothless-rounded",
  "v-d-toothless-rounded",
  "v-g-earless-rounded",
  "v-p-earless-rounded",
  "v-q-earless-corner",
  "v-y-straight-turn",
  "v-m-earless-rounded-double-arch",
  "v-n-earless-rounded-straight",
  "v-r-earless-rounded",
]
oblique = []
upright = []

# Override default building weights
# When buildPlans.<plan name>.weights is absent
# All weights would built and mapped to default shape/CSS
# IMPORTANT : Currently "menu" property only support 100, 200, 300, 400, 450, 500, 600, 700, 800, 900.
#              and "shape" properly only supports number between 100 and 900 (inclusive).

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
