[buildPlans.iosevka-mayukai-serif]      # <iosevka-custom> is your plan name
family = "Iosevka Mayukai Serif"        # Font menu family name
spacing = "normal"               # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
serifs = "sans"                  # Optional; Values: `sans` or `slab`

###################################################################################################
# Configure variants
# Optional; Whether to inherit a `ss##` variant
[buildPlans.iosevka-mayukai-serif.variants]
inherits = "ss09"

# Optional; Configure single character's variant
[buildPlans.iosevka-mayukai-serif.variants.design]
capital-a = 'straight-serifless'
capital-b = 'more-asymmetric-serifless'
capital-c = 'serifless'
capital-d = 'more-rounded-serifless'
capital-g = 'toothless-corner-serifless-hooked'
capital-u = 'toothless-rounded'
a = 'double-storey-toothless-corner'
b = 'toothless-corner'
c = 'serifless'
d = 'toothless-corner-serifless'
e = 'flat-crossbar'
f = 'flat-hook'
g = 'earless-corner'
h = 'straight'
i = 'serifed-flat-tailed'
j = 'serifed'
k = 'symmetric-connected-serifless'
l = 'serifed-flat-tailed'
m = 'earless-rounded-double-arch-short-leg'
n = 'earless-corner-straight'
p = 'earless-corner'
q = 'earless-corner'
r = 'earless-corner'
s = 'serifless'
t = 'standard'
u = 'toothless-rounded'
v = 'straight'
w = 'straight'
x = 'straight-serifless'
y = 'straight-turn'
z = 'straight-serifless'
zero = 'reverse-slashed-oval'
one = 'base-long-top-serif'
two = 'curly-neck'
three = 'flat-top'
four = 'semi-open-non-crossing'
five = 'vertical-upper-left-bar'
six = 'open-contour'
seven = 'bend-serifless'
eight = 'two-circles'
nine = 'open-contour'
asterisk = 'penta-low'
brace = 'curly-flat-boundary'
cent = 'open'
dollar = 'open'
number-sign = 'upright'
paren = 'large-contour'
percent = 'rings-continuous-slash'
underscore = 'high'
punctuation-dot = 'round'

# Optional; Configure single character's variant for Italic only; Overrides [design]
[buildPlans.iosevka-mayukai-serif.variants.italic]
a = 'single-storey-earless-corner-tailed'
b = 'toothless-rounded'
d = 'toothless-rounded-serifless'
e = 'rounded'
f = 'flat-hook-tailed'
g = 'earless-rounded'
i = 'tailed-serifed'
j = 'serifed'
k = 'cursive-serifless'
l = 'tailed-serifed'
m = 'earless-rounded-double-arch-short-leg'
n = 'earless-rounded-straight'
p = 'earless-rounded'
q = 'earless-rounded'
r = 'earless-rounded'
t = 'standard'
u = 'toothless-rounded'
y = 'cursive'

# End variant section
###################################################################################################

###################################################################################################
# Configure ligations

[buildPlans.iosevka-mayukai-serif.ligations]
inherits = "dlig"   # Optional; inherits an existing ligation set
disables = []               # Optional; disable specific ligation groups, overrides inherited ligation set
enables  = []               # Optional; enable specific ligation groups, overrides inherited ligation set

# End ligation section
###################################################################################################


###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.
# [buildPlans.iosevka-custom.weights.regular]
# shape = 400  # Weight for glyph shapes.
# menu  = 400  # Weight for the font's names.
# css   = 400  # Weight for webfont CSS.

# [buildPlans.iosevka-custom.weights.book]
# shape = 450
# menu  = 450  # Use 450 here to name the font's weight "Book"
# css   = 450

# [buildPlans.iosevka-custom.weights.bold]
# shape = 700
# menu  = 700
# css   = 700

# End weight section
###################################################################################################

###################################################################################################
# Override default building slope sets
# When this section is absent, all slopes would be built.

[buildPlans.iosevka-mayukai-serif.slopes.upright]
angle = 0             # Angle in degrees. Valid range [0, 15]
shape = "upright"     # Slope grade used for shape selection.  `upright` | `oblique` | `italic`
menu  = "upright"     # Slope grade used for naming.           `upright` | `oblique` | `italic`
css   = "normal"      # Slope grade used for webfont CSS.      `normal`  | `oblique` | `italic`

# [buildPlans.iosevka-mayukai-sonata.slopes.oblique]
# angle = 9.4
# shape = "oblique"
# menu  = "oblique"
# css   = "oblique"

[buildPlans.iosevka-mayukai-serif.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

# End slope section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#             while "menu" only supports integers between 1 and 9 (inclusive).
#             The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#             width are equal to, or a simple multiple of the unit width.
#             If you decide to use custom widths you have to define all the widths you plan to use,
#             otherwise they will not be built.

# [buildPlans.iosevka-custom.widths.normal]
# shape = 500        # Unit Width, measured in 1/1000 em.
# menu  = 5          # Width grade for the font's names.
# css   = "normal"   # "font-stretch' property of webfont CSS.

# [buildPlans.iosevka-custom.widths.extended]
# shape = 576
# menu  = 7
# css   = "expanded"

# End width section
###################################################################################################

###################################################################################################
# Character Exclusion
# Specify character ranges in the section below to exclude certain characters from the font being
# built. Remove this section when this feature is not needed.

# [buildPlans.iosevka-custom.exclude-chars]
# ranges = [[10003, 10008]]

# End character exclusion
###################################################################################################

###################################################################################################
# Compatibility Ligatures
# Certain applications like Emacs does not support proper programming liagtures provided by
# OpenType, but can support ligatures provided by PUA codepoints. Therefore you can edit the
# following section to build PUA characters that are generated from the OpenType ligatures.
# Remove this section when compatibility ligatures are not needed.

# [[buildPlans.iosevka-custom.compatibility-ligatures]]
# unicode = 57600 # 0xE100
# featureTag = 'calt'
# sequence = '<*>'

# End compatibility ligatures section
###################################################################################################

###################################################################################################
# Metric overrides
# Certain metrics like line height (leading) could be overridden in your build plan file.
# Edit the values to change the metrics. Remove this section when overriding is not needed.

# [buildPlans.iosevka-custom.metric-override]
# leading = 1250
# winMetricAscenderPad = 0
# winMetricDescenderPad = 0
# powerlineScaleY = 1
# powerlineScaleX = 1
# powerlineShiftY = 0
# powerlineShiftX = 0

# End metric override section
###################################################################################################
